### ISSUE TITLE
ამოცანა 7. FillWorld

### ISSUE THREAD

**Issue by iomodo** [oseducation/programming-methodology-java#21]
ამოხსენი ქვემოთ მოცემული ამოცანა. ამისათვის:
1. უნდა დაწერო შესაბამისი კოდი `/problem-set/ამოცანის სახელი.java` ფაილში.
2. უნდა დაწერო შესაბამისი ახსნა `/problem-set/ამოცანის სახელი.md` ფაილში.
3. განიხილე სხვადასხვა სამყაროები და ახსენი რატომ იმუშავებს კოდი ყველა შემთხვევისთვის.
3. თუკი შესაძლებელია კარგი იქნება თუ ამოცანას რამდენიმე გზით ამოხსნას დაურთავ.
4. თუკი შესაძლებელია კარგი იქნება თუ ამოცანის არასწორად ამოხსნის გზებსაც აღწერ.
5. თუკი შესაძლებელია კარგი იქნება თუ ამოცანის შესახებ ხშირად დასმულ კითხვებს და პასუხებს ჩამოწერ.

```
კარელი დგას 1x1 უჯრაზე, შეავსებინეთ მას მთელი სამყარო თითო ბრილიანტით. ანუ მთელ
სამყაროში ყველა უჯრაზე უნდა იდოს ზუსტად ერთი ბრილიანტი. ჩათვალეთ რომ საწყისი
სამყარო ცარიელი არ არის და გარკვეულ(ჩვენთვის უცნობ) უჯრებში თითო(მხოლოდ ერთი)
ბრილიანტი დევს. ამასთან გაითვალისწინეთ, რომ სამყაროს ზომები თქვენთვის უცნობია და
თქვენი პროგრამა უნდა მუშაობდეს ნებისმიერი ზომის სამყაროსათვის.
```

**Comment by tamunaa** [comment]
გავაკეთებ
