### ISSUE TITLE
ამოცანა 2. MoveBeepers

### ISSUE THREAD

**Issue by iomodo** [oseducation/programming-methodology-java#7]
ამოხსენი ქვემოთ მოცემული ამოცანა. ამისათვის:
1. უნდა დაწერო შესაბამისი კოდი `/problem-set/ამოცანის სახელი.java` ფაილში.
2. უნდა დაწერო შესაბამისი ახსნა `/problem-set/ამოცანის სახელი.md` ფაილში.
3. თუკი შესაძლებელია კარგი იქნება თუ ამოცანას რამდენიმე გზით ამოხსნას დაურთავ.
4. თუკი შესაძლებელია კარგი იქნება თუ ამოცანის არასწორად ამოხსნის გზებსაც აღწერ.
5. თუკი შესაძლებელია კარგი იქნება თუ ამოცანის შესახებ ხშირად დასმულ კითხვებს და პასუხებს ჩამოწერ.

```
ცარიელ სამყაროში კარელი დგას 1x1 უჯრაზე. 5x1 უჯრაზე დევს 10 ცალი ბრილიანტი, კარელმა ათივე
ბრილიანტი უნდა გადაიტანოს 6x1 უჯრაზე.
```

**Comment by bmana21** [comment]
გავაკეთებ
